### PR TITLE
Implementation of the pull request diff json request/response

### PR DESCRIPTION
**Pull request by dwdking**
Hey, thanks for the project. It helped me out greatly. I needed some additional functionality so I added portions to implemented the pull request diff. Specifically parsing and being able to view this resource /projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/diff

This is the first time I've done much in python so feel free to be as critical as possible.

### CODE REVIEW

**Comment by tonytamsf** [comment]
@dwdking thanks for the contribution.  Could you merge changes from master and re-trigger Travis CI?

**Comment by dwdking** [comment]
@tonytamsf, give me a bit. I haven't looked at this for a bit and don't have the project setup.

**Comment by tonytamsf** [comment]
Thank @dwdking

**Comment by dwdking** [comment]
@tonytamsf, I've merged in the changes from master

**Comment by tonytamsf** [comment]
Thank you @dwdking

**Pull request merged**
